name: Verify Artifacts

on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  apply-templates:
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Apply Templates
            run: ./parallel.sh apply-templates.sh

          - name: '"true" binaries'
            run: |
              cd 'true'
              docker build --pull --tag 'tianon/true:builder' --target asm --file Dockerfile.all .
              for binary in \
                'true-asm' \
                'true-yolo' \
              ; do
                test -s "$binary"
                rm -v "$binary"
                docker run --rm 'tianon/true:builder' tar -cC '/true' "$binary" | tar -xv
                test -s "$binary"
              done

          - name: '"true" OCI images'
            run: |
              cd 'true'
              test -d oci
              test -d yoloci
              rm -rv oci yoloci
              ./oci.sh oci 'true-asm'
              ./oci.sh yoloci 'true-yolo'
            fetchAllCommits: true # we need more commits to get the right "created" values

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ !matrix.fetchAllCommits && 1 || 0 }}

      - name: ${{ matrix.name }}
        run: ${{ matrix.run }}

      - name: Git Diff
        run: git diff --exit-code
